### ISSUE TITLE
Semicolons

### ISSUE THREAD

**Issue by eliperelman** [devtees/shirt-ideas#13]
I've been wanting a shirt lately that says:

I :heart: ;
(I heart semicolons).

**Comment by jglovier** [comment]
With unicode character:

![image](https://cloud.githubusercontent.com/assets/1319791/5741498/5d44149e-9bd9-11e4-92e4-6b8c1fa228dc.png)

**Comment by Pembrokeshirecommunityit** [comment]
I think i put in wrong place just B4? so second attempt...I borrowed your T-shirt jglovier hope you dont mind?
![github](https://cloud.githubusercontent.com/assets/10488033/5768995/fadd190a-9d0d-11e4-8ee5-3a2f40260d9e.jpg)

**Comment by jglovier** [comment]
Final design.

![iheartsemicolons-mock-black](https://cloud.githubusercontent.com/assets/1319791/10864612/4786dfc6-7fca-11e5-9f61-97f60b841963.jpg)

**Comment by jglovier** [comment]
This shirt is now available for purchase at: http://devtees.com/collections/fall-2015-collection/products/semicolon-love

Thanks for the input everyone!

:zap: :zap: :zap:

**Comment by eliperelman** [comment]
:clap:
