### ISSUE TITLE
Reprint of the Hacker 1 tees?

### ISSUE THREAD

**Issue by joakim** [devtees/shirt-ideas#21]
Of the [awesome Hacker 1 tees](http://devtees.com/collections/hacker-tees), there are only shirts left from size XL and up. I'd love to get me one in S. Will there be reprints of these awesome tees? :+1:

**Comment by jglovier** [comment]
Closing this out because there are no plans to reprint the Hacker 1 tee in the immediate future. But thanks for your feedback!
