### ISSUE TITLE
Development Process Flowchart Tee

### ISSUE THREAD

**Issue by bnb** [devtees/shirt-ideas#22]
I don't know where I saw it, but the other day I saw a simple flow chart of the programming process. where there was one column of steps in the development process, with guides (i.e. `<-- no`, `<-- fail`, `succeed -->`, and `yes -->` ) to cycle back to previous steps if the result changes. It would be awesome to have a flow chart tee of the dev process. Some steps I can think of:

```
 Conceptualize
          |
          V 
        Plan  <----------- |
          |                |
          V                |
        Code  <--  |       |
          |        |       |
          V        |       |
        Test  -----| ----- | 
          |
          V 
        Push
```

There were several more in the example I saw, and I'm sure some of you will be able to think of more.

**Comment by jglovier** [comment]
I think this could make a really interesting design, but I'm closing this for now as it's not going to make it into the next round of shirts. I'll revisit it later.
