### ISSUE TITLE
PR or STFU

### ISSUE THREAD

**Issue by kwoodfriend** [devtees/shirt-ideas#26]
Possibly use a "pull request" type icon/image with an "STFU" after

**Comment by MaximRouiller** [comment]
What about (Pull Request Icon) or (Fork Icon) It?

It would read as Pull Request or Fork it. Which could mean "Pull Request or Fuck it." :stuck_out_tongue:

**Comment by billinghamj** [comment]
:+1: I would definitely buy the tee mocked up above by @bnb. Less interested if it doesn't say STFU/GTFO/etc. - the point of it is to be quite in your face.

**Comment by MaximRouiller** [comment]
Except that if it does say STFU/GTFO, I'm not wearing it except on the weekend which defeats the whole purpose. Not all clients/employer are as friendly as to let anything on a shirt.

And if I'm not wearing it, I'm not buying it. :smile:

**Comment by jglovier** [comment]
After some thought, and because I design shirts for the GitHub Shop as well, this would be a better fit for the [GitHub Shop](https://github.myshopify.com/), not Dev Tees. Thanks for the suggestion, and I'll consider it for a GitHub tee concept. :sparkles:
