### ISSUE TITLE
There is a gem for that!

### ISSUE THREAD

**Issue by mcka1n** [devtees/shirt-ideas#29]
**Context**

Being a Ruby developer, sometimes you are so pumped to build a new gem from the scratch but then you find that there is already a gem for that! haha.

Ruby developers love to create and use gems, that's what keeps cool the community. 

**Here are some examples:**

![screen shot 2014-10-12 at 9 31 58 pm](https://cloud.githubusercontent.com/assets/1958982/4608806/f5dc1650-5289-11e4-8107-47c17fa34752.png)

Not sure if this one is better:

![screen shot 2014-10-12 at 9 32 19 pm](https://cloud.githubusercontent.com/assets/1958982/4608810/00bb6fc6-528a-11e4-83db-c9731f8710f7.png)

**Comment by woodall** [comment]
I dig the latest one.

**Comment by jglovier** [comment]
Final design comp:

![image](https://cloud.githubusercontent.com/assets/1319791/10314605/ae00d6e0-6c23-11e5-97b2-6b4883c5a937.png)

**Comment by woodall** [comment]
fancy!

**Comment by kwoodfriend** [comment]
Love the colors!

**Comment by MaximRouiller** [comment]
Awesome work @jglovier !

**Comment by mcka1n** [comment]
It's awesome!! Can't wait to have my t-shirt! ^.^ 

Very good job! @jglovier

**Comment by jglovier** [comment]
This shirt is now available for purchase at: http://devtees.com/collections/fall-2015-collection/products/gem-for-that
