### ISSUE TITLE
Design (and) Develop shirt

### ISSUE THREAD

**Issue by bnb** [devtees/shirt-ideas#30]
I came up with a shirt idea that I rather like, "design (and) develop". I know this is dev tees, so I understand if the design part isn't appealing. Two variants. Let me know what you think!

![Design - Develop](https://i.imgur.com/ASmHFZc.jpg)

![Design - & - Develop](https://i.imgur.com/Jib5jYr.jpg)

**Comment by woodall** [comment]
I dig it!
Some say the 'x' thing is out, but I like that one with the pencil and keyboard. 
I'd change the keyboard to be maybe a single key, like the return button or something.

**Comment by jglovier** [comment]
@woodall ooo I like that idea. :sparkles:

**Comment by jglovier** [comment]
This one is really fun, and I def want to do it, but punting for now. :football: Will revisit later.

**Comment by woodall** [comment]
Can I take a crack at the design? I've been known to design a shirt or two in my previous life :minidisc:

**Comment by jglovier** [comment]
@woodall thanks for the offer, but for legal copyright & trademark reasons I design all the stuff that gets printed on Dev Tees. Nothing stopping you from making a concept though! Just that I only print stuff I've created.
