### ISSUE TITLE
JavaScript - Your tears are delicious

### ISSUE THREAD

**Issue by reverentgeek** [devtees/shirt-ideas#31]
Inspired by [this exchange on Twitter](https://twitter.com/bryan_hunter/status/526838987340906496).

From Alex Robson (@arobson): 

I was thinking that a lot of JS folks would enjoy having a shirt that has a little fun with all of the angst and hand-wringing around JavaScript. "JavaScript says your tears are delicious" is a t-shirt I would definitely wear :) I actually think fans and critics alike would enjoy it.

**Comment by una** [comment]
love this :)

**Comment by jglovier** [comment]
Finally got around to re-working out the smile. Hold onto your butts, these are coming :soon:. :grin:

![image](https://cloud.githubusercontent.com/assets/1319791/10107687/d3e2e156-638a-11e5-9274-5080279f47af.png)

**Comment by jglovier** [comment]
Thoughts on yellow print vs white?

![image](https://cloud.githubusercontent.com/assets/1319791/10107740/1edccf82-638b-11e5-9f3e-f0cd91529ed9.png)

![image](https://cloud.githubusercontent.com/assets/1319791/10107720/fe49ce82-638a-11e5-91f7-d69dada5f062.png)

**Comment by reverentgeek** [comment]
I prefer the white, because uh... teeth are _generally_ white. I wonder if having "delicious" in white with the previous text in yellow would make it more visually striking?

**Comment by reverentgeek** [comment]
Maybe keep the tears white, too.

**Comment by jglovier** [comment]
@reverentgeek yeah, good point; i'll just keep it black and white.

**Comment by jglovier** [comment]
Thinking of doing a two color print on a banana colored shirt instead of white on black. Thoughts?

![javascript-says-mock-banana](https://cloud.githubusercontent.com/assets/1319791/10869271/f36d5772-8077-11e5-9096-ab52d98d1545.jpg)

**Comment by reverentgeek** [comment]
Yeah, that rocks.

**Comment by una** [comment]
That one!

**Comment by bnb** [comment]
:100: on that last one.

**Comment by jglovier** [comment]
This shirt is now available for purchase. I settled on doing BOTH yellow and black tees, because I got so much response for both on Twitter. :smile:

Get the banana one: http://devtees.com/collections/fall-2015-collection/products/javascript-says

Get the Black one: http://devtees.com/collections/fall-2015-collection/products/javascript-says-black

Thanks for the input everyone!

:zap: :zap: :zap:

**Comment by GantMan** [comment]
Dude, get the XL back in stock man!   I got shirts to show off!
