### ISSUE TITLE
"To <b>, or not to <b>"

### ISSUE THREAD

**Issue by bnb** [devtees/shirt-ideas#32]
I think most of us know the answer to this question. However, I thought it was a silly quote. I really dig the <table> flip, and thought it would be fun to try to come up with a few literary dev shirt ideas. This is probably one of the most famous quotes in the western hemisphere, and the <b> element fits in really, really well--perfectly, actually--with it. 

Quote:
```HTML
To <b>, or not to <b>
```

Could also do something a bit more silly,
```
To <b>, or not to </b>
```

**Comment by jglovier** [comment]
This one is a fun idea, but a little too literal to be very visually interesting. I'm leaning away from the suggestions that basically just result in a design that is only text. But thanks for the suggestion @bnb! :sparkles:
