### ISSUE TITLE
No Comment

### ISSUE THREAD

**Issue by woodall** [devtees/shirt-ideas#33]
How about a list of No and Comment from different languages.

.  # No
<!- Nine ->
// nil
/* nay */
;; uh-uh

**Comment by jglovier** [comment]
Thanks for the suggestion, but closing this one out. It's a fun idea, but a little too literal to be visually very interesting.

**Comment by woodall** [comment]
I'm willing to admit the best of my t-shirt days are behind me :city_sunset: 

Also, I hope you don't mind that I mentioned you in my [Github application](https://github.com/woodall/technical-support) I submitted yesterday. :sunrise_over_mountains:

**Comment by jglovier** [comment]
@woodall no, not at all. That's great! :metal:

**Comment by jglovier** [comment]
>I'm willing to admit the best of my t-shirt days are behind me

I wouldn't say that! Just that for Dev Tees I'm trying to do as few text only shirts as possible.
