### ISSUE TITLE
Mo' Pixels Mo' Money

### ISSUE THREAD

**Issue by commadelimited** [devtees/shirt-ideas#34]
Based on a [conversation with Jonathan Stark on Twitter](https://twitter.com/eisaksen/status/553311882992701441). The concept was that as screens get bigger we, as developers, should be able to charge people by the pixel. I stated that I'd make a killing with the new 4k monitors.

Thus was born the Mo' Pixels Mo' Money image:

![b63kz-gcyaavug3](https://cloud.githubusercontent.com/assets/563460/5693693/3c139566-98ef-11e4-9559-583a55caa5e9.png)

**Comment by Nevraeka** [comment]
:+1 @commadelimited

**Comment by jglovier** [comment]
Love the concept! I'll riff a little on the artwork and post soon.

**Comment by Nevraeka** [comment]
I want one!

**Comment by MaximRouiller** [comment]
Pixel-art freelancer/developer with "I charge by the ~~hour~~ pixel" under it would be interesting. :smile:

**Comment by jglovier** [comment]
Fun concept, but it's not going to make it into the next run. Closing for now, will revisit later.

Thanks for the suggestion @commadelimited! :sparkles: :shirt: :metal:

**Comment by Nevraeka** [comment]
:+1:  Thank you @jglovier

**Comment by Nevraeka** [comment]
@jglovier will it be available in 3x?

**Comment by jglovier** [comment]
@nevraeka this suggestion has been archived for later, but yes all new Dev Tees are offered in 3X (at least during preorder)
