### ISSUE TITLE
Love that ;

### ISSUE THREAD

**Issue by Pembrokeshirecommunityit** [devtees/shirt-ideas#35]
Your doing T-shirt right? I'm probably way off but here.
![github](https://cloud.githubusercontent.com/assets/10488033/5768955/8e4ccc72-9d0d-11e4-8699-3d1596272440.jpg)

**Comment by billinghamj** [comment]
This one is way too complex I think

**Comment by jglovier** [comment]
>This one is way too complex I think

Yeah, agreed. Thanks just the same for the suggestion, @Pembrokeshirecommunityit!
