### ISSUE TITLE
"There's a package for that"

### ISSUE THREAD

**Issue by carlvlewis** [devtees/shirt-ideas#37]
With nearly 140,000 published NPMs, there's almost always an node module for that.

![t_shirt_psd_by_grahamphisherdotcom](https://cloud.githubusercontent.com/assets/1697569/7111093/41c41b1a-e189-11e4-8db4-e1b3b04f55bd.png)

**Comment by mcka1n** [comment]
I got the idea! but I think it should be something like: "There is a package/module for that" right?

Because NPM is just the Node Package Manager.

:)

**Comment by jglovier** [comment]
@carlvlewis thanks for the suggestion and concept art. :heart: I do agree with @mcka1n that "There is a package for that" is probably more appropriate, but there is actually a [Ruby themed shirt](https://github.com/devtees/shirt-ideas/issues/29) of similar nature in the works for the next run, so this one probably won't happen for a little while, although I think it would make a great candidate for :soon:. :metal: :zap: :shirt:

**Comment by carlvlewis** [comment]
It's actually supposed to be "There's a module for that" if you look at crossed letters but I see your points. Thanks! 

Sent from Outlook




On Wed, Apr 15, 2015 at 7:44 PM -0700, "Joel Glovier" <notifications@github.com> wrote:












@carlvlewis thanks for the suggestion and concept art.  I do agree with @mcka1n that "There is a package for that" is probably more appropriate, but there is actually a Ruby themed shirt of similar nature in the works for the next run, so this one probably won't happen for a little while, although I think it would make a great candidate for .

**Comment by billinghamj** [comment]
For node, 'module' refers to a single file. 'package' refers to something published on npm. So in this instance, I think it's more correct to say "there's a package for that", similarly to "there's an app for that".

**Comment by jglovier** [comment]
Closing for now as it's not going to make it into the next round of shirts, and we already have the same concept for ruby gems in the next round. Will revisit later.

Thanks for the suggestion.
