### ISSUE TITLE
Look of Disapproval

### ISSUE THREAD

**Issue by jglovier** [devtees/shirt-ideas#4]
`ಠ_ಠ`

## Mockups

![img](http://f.cl.ly/items/1v2w2E2O131C3H3F0p1m/disapproval-mockup.jpg)

**Comment by MaximRouiller** [comment]
"We're using IE8" above the face would make it. :stuck_out_tongue:

**Comment by jglovier** [comment]
I always like having no text as opposed to text because without text you get to fill in the meaning mentally however you'd like, but this might be a fun caption:

![image](https://cloud.githubusercontent.com/assets/1319791/10869682/7262c150-8084-11e5-95ac-19b7c449cdbe.png)

**Comment by Rowno** [comment]
I vote for no text.

**Comment by jglovier** [comment]
This design is now available for purchase at: http://devtees.com/collections/fall-2015-collection/products/look-of-disapproval

Thanks for the feedback everyone!

:zap::zap::zap:
