### ISSUE TITLE
Tech support

### ISSUE THREAD

**Issue by jglovier** [devtees/shirt-ideas#40]
Everyone who is a developer or designer has likely been asked somewhere between 1 - 1,000,000 times by a friend, family member, or stranger, "Oh your a computer person! Can you fix my ______??"

I feel like there's a really shirt concept in here somewhere, like, "No, I can't fix your computer/modem/router/phone/wifi".

**Comment by jobbogamer** [comment]
Similar, although "will not" is a bit more hostile than "can't": http://www.thinkgeek.com/product/388b/

**Comment by jglovier** [comment]
Oh I didn't realize that was an existing shirt. Thanks for the heads up. I'm not really interested in replicating existing concepts, so I'm going to close this one out.
