### ISSUE TITLE
A new Open Source shirt concept

### ISSUE THREAD

**Issue by jglovier** [devtees/shirt-ideas#42]
The [Set Code Free]() shirt has been one of my most popular designs. I think it'd be cool to do a new design celebrating open source software, but at the moment I'm at a loss for clever concepts beyond just cool typography (which is def an option). 

Any ideas for a clever new OS tee concept? If even just typography, any ideas for how it would read? Something like "I :heart: Open Source" could be legit, but is kind of boring. Of course, a lot of it is in the design execution, but starting with a really compelling concept is the best first step.

**Comment by MaximRouiller** [comment]
Set Code Free

Could be stylized "Code" word with wings flying out of a cage. You could even play with this old quote:

“If you love something, set it free. If it comes back, it was, and always will be yours. If it never returns, it was never yours to begin with.”

**Comment by jglovier** [comment]
@MaximRouiller hmm, that's an interesting concept for a v2 "Set Code Free" shirt! I'm really interested in exploring a completely alternative concept for an Open Source tee.

**Comment by MaximRouiller** [comment]
Same image ("code" with wings going out of the cage) with just the words "If you love something, set it free"

Could almost have a line under "Github. Setting code free since 2007" :smile:

**Comment by MaximRouiller** [comment]
I understand the need to keep things minimal as to not overcrowd the shirt. You need something small, that talks more than words and that people can understand quickly.  Not an easy feat. :)

**Comment by jglovier** [comment]
>Could almost have a line under "Github. Setting code free since 2007"

To be clear, Dev Tees is my personal project and in no way affiliated with GitHub, so that would be a no-no.

**Comment by MaximRouiller** [comment]
Hence the "Almost" ;-)

**Comment by jglovier** [comment]
Still drawing a blank on concepts, and this isn't going to make it into the next round of tees, so I'm closing this for now. Will revisit later.
