### ISSUE TITLE
Pixel shell

### ISSUE THREAD

**Issue by jglovier** [devtees/shirt-ideas#44]
Pixel styled shell themed tee.

<img width="504" alt="screen shot 2015-10-27 at 12 33 50 am" src="https://cloud.githubusercontent.com/assets/1319791/10749583/6c6fc19e-7c42-11e5-9e9a-0ffbcd1a5d9f.png">

**Comment by reybango** [comment]
Love this

**Comment by jglovier** [comment]
@reybango :heart: :metal:

**Comment by jglovier** [comment]
This shirt is now available for purchase at: http://devtees.com/collections/fall-2015-collection/products/pixel-shell

:zap: :zap: :zap:

**Comment by reybango** [comment]
Pre-ordered mine. Rocks. <3

**Comment by reybango** [comment]
Pre-ordered mine. Rocks. <3

**Comment by jglovier** [comment]
@reybango :heart: :metal: :zap: :shirt:

**Comment by MaximRouiller** [comment]
Look like Powershell :stuck_out_tongue:
