### ISSUE TITLE
Power By Disappears 

### ISSUE THREAD

**Issue by viruscmd** [devtees/shirt-ideas#45]
When you hover over Joel Glovier in the footer the words "Powered By" disappear.

**Comment by viruscmd** [comment]
Also the same happens when you hover over shopify "Joel Glovier" disappears.

**Comment by jglovier** [comment]
LOL what a strange bug. Thanks for pointing it out.

**Comment by jglovier** [comment]
This appears to be a Chrome bug as I can't reproduce it in Firefox or Safari. Going to keep digging to find a workaround.

**Comment by jglovier** [comment]
Looked for stray markup and even checked the HTML validator for clues, but couldn't find anything. Closing as a Chrome bug. Thanks again for the heads up.
