### ISSUE TITLE
Typeface tee

### ISSUE THREAD

**Issue by jglovier** [devtees/shirt-ideas#5]
## Mockup

![img](http://f.cl.ly/items/0A400P35272S0o2S0p24/typeface-mockup-brown.jpg)

![img](http://f.cl.ly/items/0k210X3L3E0J171q2w3N/typeface-mockup.jpg)

**Comment by MaximRouiller** [comment]
That's very good! Love it :)

**Comment by jglovier** [comment]
Final color design. 

![typeface-mockup-gray](https://cloud.githubusercontent.com/assets/1319791/10865298/732a869c-7fdd-11e5-8366-68f8af516dd3.jpg)

**Comment by jglovier** [comment]
This design is now available for purchase at: http://devtees.com/collections/fall-2015-collection/products/typeface

Thanks for the feedback everyone!

:zap::zap::zap:
